apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: python-server
        image: kabbilkarthi/helloworld:hw1 
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
